package pl.polsl.ltc2017.model;

public class Queries {

	public static final String[] COMPLEX_QUERIES = {
			"SELECT MAX(HYPER-PATH LENGTH)",
			"SELECT SYNSET WITH MIN(HYPO-PATHS)",
			"SELECT SYNSET WITH MAX(HYPO-PATHS)",
			"SELECT SYNSET WITH MIN(HYPER-PATHS)",
			"SELECT SYNSET WITH MAX(HYPER-PATHS)" };

	public static final String[] STATS_QUERIES_S = {
			"SELECT HIGHEST HYPERNYM FOR SYNSET X",
			"SELECT LOWEST HYPONYM FOR SYNSET X",
			"SELECT COUNT(HYPO-PATHS) FOR SYNSET X",
			"SELECT COUNT(HYPER-PATHS) FOR SYNSET X" };

	public static final String[] STATS_QUERIES_L = {
			"SELECT HIGHEST HYPERNYM FOR LITERAL X",
			"SELECT LOWEST HYPONYM FOR LITERAL X",
			"SELECT COUNT(HYPO-PATHS) FOR LITERAL X",
			"SELECT COUNT(HYPER-PATHS) FOR LITERAL X" };

	public static final String[] STATS_QUERIES_LS = {
			"SELECT HIGHEST HYPERNYM FOR LITERAL X AND SENSE Y",
			"SELECT LOWEST HYPONYM FOR LITERAL X AND SENSE Y",
			"SELECT COUNT(HYPO-PATHS) FOR LITERAL X AND SENSE Y",
			"SELECT COUNT(HYPER-PATHS) FOR LITERAL X AND SENSE Y" };
}